version: "3.9"
services:
  api:
    env_file:
      - ./desafio-fullstack-api/.env
    container_name: desafio-fullstack-api
    build: ./desafio-fullstack-api/
    ports:
      - 8080:8080
    networks:
      - bd-network
    links:
      - postgres

  postgres:
    env_file:
      - ./desafio-fullstack-api/.env
    container_name: postgres
    image: postgres
    networks:
      - bd-network
    environment:
      # POSTGRES_HOST: ${POSTGRES_HOST}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_USER: ${POSTGRES_USER}
      # POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  # migrate:
  #   build: ./desafio-fullstack-api/
  #   command: pnpm db:migrate
  #   networks:
  #     - bd-network
  #   depends_on:
  #     - postgres

  web:
    env_file:
      - ./desafio-fullstack-web/.env
    container_name: desafio-fullstack-web
    build: ./desafio-fullstack-web/
    ports:
      - 3000:3000
    networks:
      - bd-network
    links:
      - api

networks:
  bd-network:
    driver: bridge

volumes:
  pgdata:
